# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
  - test
  - build
  - deploy_dev

cache:
  paths:
    - node_modules/
  key:
    files:
      - package.json

typescript test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run tsc

eslint test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run lint

unit test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run test

build app android:
  when: manual
  only:
    - tags
  image: reactnativecommunity/react-native-android
  stage: build
  script:
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo $ANDROID_KEYSTORE | base64 -d > android/app/topic.keystore
    - sh gitlab/generate-dotenv.sh > .ENV
    - echo "unsafe-perm = true" > .npmrc
    - npm install
    - cd android/scripts
    - './genapks-gitlab.sh'
  artifacts:
    paths:
      - './android/scripts/apks'

build web:
  only:
    - tags
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - export IMG_FULLNAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker build -t $IMG_FULLNAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMG_FULLNAME

deploy web dev:
  stage: deploy_dev
  image: alpine
  tags:
    - devserver
  only:
    - tags
  environment:
    name: dev
    url: https://dev.topicapp.fr
  resource_group: devdeploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh gitlab@ssh-dev.topicapp.fr "cd /home/topic/config/dev_main/topic && python <<< \"import envreplacer; envreplacer.replace('TOPIC_VERSION_MOBILE','$CI_COMMIT_TAG')\" && sudo -u topic /home/topic/config/dev_main/topic/deploy.sh"

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: nodejs-scan
  stage: test

variables:
  DS_DEFAULT_ANALYZERS: 'retire.js, gemnasium'

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
