# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
  - test
  - build

cache:
  paths:
    - node_modules/
  key:
    files:
      - package.json

typescript test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run tsc

eslint test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run lint

unit test:
  stage: test
  image: node:12
  before_script:
    - echo "unsafe-perm = true" > .npmrc
    - npm install --prefer-offline
  script:
    - npm run test

build app android:
  when: manual
  only:
    - tags
  image: reactnativecommunity/react-native-android
  stage: build
  script:
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo $ANDROID_KEYSTORE | base64 -d > android/app/topic.keystore
    - sh gitlab/generate-dotenv.sh > .ENV
    - echo "unsafe-perm = true" > .npmrc
    - npm install
    - cd android/scripts
    - './genapks-gitlab.sh'
  artifacts:
    paths:
      - './android/scripts/apks'

build web:
  only:
    - tags
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - export IMG_FULLNAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker build -t $IMG_FULLNAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMG_FULLNAME

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: nodejs-scan
  stage: test

variables:
  DS_DEFAULT_ANALYZERS: 'retire.js, gemnasium'

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
