stages:
  - build

build app android:
  only:
    - tags
  image: reactnativecommunity/react-native-android
  stage: build
  script:
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - base64 -d $ANDROID_KEYSTORE > android/app/topic.keystore
    - sh gitlab/generate-dotenv.sh > .ENV
    - npm install
    - cd android/scripts
    - yes | ./genapks.sh
  artifacts:
    paths:
      - ./android/scripts/apks
