FROM node:12-alpine AS builder

WORKDIR /data

COPY package*.json ./

RUN apk update && apk add git
RUN npm install && npm install --save react-native-web react-native-linear-gradient

COPY . .

RUN npm cache clean --force && npm install -g expo-cli
RUN expo build:web

FROM nginx:1.19.3-alpine

# remove default.conf
RUN rm -rf /etc/nginx/conf.d/*

# remove html generated by nginx
RUN rm -rf /usr/share/nginx/html/*

WORKDIR /usr/share/nginx/html

# copy nginx conf
COPY web.nginx.conf /etc/nginx/conf.d

# copy static site
COPY --from=builder /data/web-build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
